version: 2
root-markers:
  - .git/
  - package.json
lint-debounce: 1s

tools:
  prettierd: &prettierd
    format-command: 'prettierd "${INPUT}"'
    format-stdin: true
  # Lua
  stylua: &stylua
    format-command: "stylua -s --color Never -"
    format-stdin: true
    root-markers:
      - stylua.toml
      - .stylua.toml
  # Go
  gofmt: &gofmt
    format-command: "gofmt"
    format-stdin: true
    root-markers:
      - go.mod
      - go.sum
  goimports: &goimports
    format-command: "goimports"
    format-stdin: true
    root-markers:
      - go.mod
      - go.sum
  # Terraform
  terraform-fmt: &terraform-fmt
    format-command: "terraform fmt -"
    format-stdin: true
  # OCaml
  ocamlformat: &ocamlformat
    format-command: 'ocamlformat --name "${INPUT}" -'
    format-stdin: true
    root-markers:
      - .ocamlformat
languages:
  lua:
    - <<: *stylua
  go:
    - <<: *gofmt
    - <<: *goimports
  ocaml:
    - <<: *ocamlformat
  # web
  html:
    - <<: *prettierd
  markdown:
    - <<: *prettierd
  javascript:
    - <<: *prettierd
  javascriptreact:
    - <<: *prettierd
  typescript:
    - <<: *prettierd
  typescriptreact:
    - <<: *prettierd
  # config
  json:
    - <<: *prettierd
  jsonc:
    - <<: *prettierd
  yaml:
    - <<: *prettierd
  terraform:
    - <<: *terraform-fmt
