"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""
scan_timeout = 30
command_timeout = 300

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
truncate_to_repo = true

[aws]
format = 'on [$symbol($profile)]($style) '
