#!/bin/bash
# vim: ft=sh :

command="$(jq -nc '{command: "open", now: now, url: $url}' --arg url "$1" | base64)"
text="$(printf "\033]1337;SetUserVar=%s=%s\007" command "$command")"
wezterm cli spawn sh -c "echo \"$text\"; sleep 1" >/dev/null
